"""Every ECMA-376 preset"s text rectangle (``a:rect``), as guide names or literals.

**Generated file -- do not edit.**  Regenerate with::

    python3 tools/derive_preset_text_rects.py --source presetShapeDefinitions.xml

Source: ECMA-376 Part 1, 5th edition (December 2016), electronic addendum
``OfficeOpenXML-DrawingMLGeometries.zip`` -> ``presetShapeDefinitions.xml``
SHA-256 ``2f7c868d857c1e3c4b5a6068759fe0e07d77ad58377a6618d1b02ba3507b6939``.  A definition without an ``a:rect`` is its whole box; ``upArrow``, which
that file does not define, mirrors ``downArrow``"s (``SUPPLEMENTS`` in the tool).

Each entry is ``name -> (l, t, r, b)``, evaluated against the preset"s guides in
:data:`~ooxml_common.drawingml.presets.PRESETS` by
:func:`~ooxml_common.drawingml.geometry.text_rect`.
"""

# fmt: off
PRESET_TEXT_RECTS: dict = {
    "accentBorderCallout1": ("l", "t", "r", "b"),
    "accentBorderCallout2": ("l", "t", "r", "b"),
    "accentBorderCallout3": ("l", "t", "r", "b"),
    "accentCallout1": ("l", "t", "r", "b"),
    "accentCallout2": ("l", "t", "r", "b"),
    "accentCallout3": ("l", "t", "r", "b"),
    "actionButtonBackPrevious": ("l", "t", "r", "b"),
    "actionButtonBeginning": ("l", "t", "r", "b"),
    "actionButtonBlank": ("l", "t", "r", "b"),
    "actionButtonDocument": ("l", "t", "r", "b"),
    "actionButtonEnd": ("l", "t", "r", "b"),
    "actionButtonForwardNext": ("l", "t", "r", "b"),
    "actionButtonHelp": ("l", "t", "r", "b"),
    "actionButtonHome": ("l", "t", "r", "b"),
    "actionButtonInformation": ("l", "t", "r", "b"),
    "actionButtonMovie": ("l", "t", "r", "b"),
    "actionButtonReturn": ("l", "t", "r", "b"),
    "actionButtonSound": ("l", "t", "r", "b"),
    "arc": ("il", "it", "ir", "ib"),
    "bentArrow": ("l", "t", "r", "b"),
    "bentConnector2": ("l", "t", "r", "b"),
    "bentConnector3": ("l", "t", "r", "b"),
    "bentConnector4": ("l", "t", "r", "b"),
    "bentConnector5": ("l", "t", "r", "b"),
    "bentUpArrow": ("l", "y2", "x4", "b"),
    "bevel": ("x1", "x1", "x2", "y2"),
    "blockArc": ("il", "it", "ir", "ib"),
    "borderCallout1": ("l", "t", "r", "b"),
    "borderCallout2": ("l", "t", "r", "b"),
    "borderCallout3": ("l", "t", "r", "b"),
    "bracePair": ("il", "il", "ir", "ib"),
    "bracketPair": ("il", "il", "ir", "ib"),
    "callout1": ("l", "t", "r", "b"),
    "callout2": ("l", "t", "r", "b"),
    "callout3": ("l", "t", "r", "b"),
    "can": ("l", "y2", "r", "y3"),
    "chartPlus": ("l", "t", "r", "b"),
    "chartStar": ("l", "t", "r", "b"),
    "chartX": ("l", "t", "r", "b"),
    "chevron": ("il", "t", "ir", "b"),
    "chord": ("il", "it", "ir", "ib"),
    "circularArrow": ("il", "it", "ir", "ib"),
    "cloud": ("il", "it", "ir", "ib"),
    "cloudCallout": ("il", "it", "ir", "ib"),
    "corner": ("l", "it", "ir", "b"),
    "cornerTabs": ("dx", "dx", "x1", "y1"),
    "cube": ("l", "y1", "x4", "b"),
    "curvedConnector2": ("l", "t", "r", "b"),
    "curvedConnector3": ("l", "t", "r", "b"),
    "curvedConnector4": ("l", "t", "r", "b"),
    "curvedConnector5": ("l", "t", "r", "b"),
    "curvedDownArrow": ("l", "t", "r", "b"),
    "curvedLeftArrow": ("l", "t", "r", "b"),
    "curvedRightArrow": ("l", "t", "r", "b"),
    "curvedUpArrow": ("l", "t", "r", "b"),
    "decagon": ("x1", "y2", "x4", "y3"),
    "diagStripe": ("l", "t", "x3", "y3"),
    "diamond": ("wd4", "hd4", "ir", "ib"),
    "dodecagon": ("x1", "y1", "x4", "y4"),
    "donut": ("il", "it", "ir", "ib"),
    "doubleWave": ("il", "it", "ir", "ib"),
    "downArrow": ("x1", "t", "x2", "y2"),
    "downArrowCallout": ("l", "t", "r", "y2"),
    "ellipse": ("il", "it", "ir", "ib"),
    "ellipseRibbon": ("x2", "q1", "x5", "y6"),
    "ellipseRibbon2": ("x2", "y6", "x5", "rh"),
    "flowChartAlternateProcess": ("il", "il", "ir", "ib"),
    "flowChartCollate": ("wd4", "hd4", "ir", "ib"),
    "flowChartConnector": ("il", "it", "ir", "ib"),
    "flowChartDecision": ("wd4", "hd4", "ir", "ib"),
    "flowChartDelay": ("l", "it", "ir", "ib"),
    "flowChartDisplay": ("wd6", "t", "x2", "b"),
    "flowChartDocument": ("l", "t", "r", "y1"),
    "flowChartExtract": ("wd4", "vc", "x2", "b"),
    "flowChartInputOutput": ("wd5", "t", "x5", "b"),
    "flowChartInternalStorage": ("wd8", "hd8", "r", "b"),
    "flowChartMagneticDisk": ("l", "hd3", "r", "y3"),
    "flowChartMagneticDrum": ("wd6", "t", "x2", "b"),
    "flowChartMagneticTape": ("il", "it", "ir", "ib"),
    "flowChartManualInput": ("l", "hd5", "r", "b"),
    "flowChartManualOperation": ("wd5", "t", "x3", "b"),
    "flowChartMerge": ("wd4", "t", "x2", "vc"),
    "flowChartMultidocument": ("l", "y2", "x5", "y8"),
    "flowChartOfflineStorage": ("wd4", "t", "x4", "vc"),
    "flowChartOffpageConnector": ("l", "t", "r", "y1"),
    "flowChartOnlineStorage": ("wd6", "t", "x2", "b"),
    "flowChartOr": ("il", "it", "ir", "ib"),
    "flowChartPredefinedProcess": ("wd8", "t", "x2", "b"),
    "flowChartPreparation": ("wd5", "t", "x2", "b"),
    "flowChartProcess": ("l", "t", "r", "b"),
    "flowChartPunchedCard": ("l", "hd5", "r", "b"),
    "flowChartPunchedTape": ("l", "hd5", "r", "ib"),
    "flowChartSort": ("wd4", "hd4", "ir", "ib"),
    "flowChartSummingJunction": ("il", "it", "ir", "ib"),
    "flowChartTerminator": ("il", "it", "ir", "ib"),
    "foldedCorner": ("l", "t", "r", "y2"),
    "frame": ("x1", "x1", "x4", "y4"),
    "funnel": ("l", "t", "r", "b"),
    "gear6": ("xD5", "yA1", "xA1", "yD2"),
    "gear9": ("xA8", "yD1", "xD1", "yD3"),
    "halfFrame": ("l", "t", "r", "b"),
    "heart": ("il", "hd4", "ir", "ib"),
    "heptagon": ("x2", "y1", "x5", "ib"),
    "hexagon": ("il", "it", "ir", "ib"),
    "homePlate": ("l", "t", "ir", "b"),
    "horizontalScroll": ("ch", "ch", "x4", "y6"),
    "irregularSeal1": ("x5", "y3", "x21", "y9"),
    "irregularSeal2": ("x5", "y3", "x19", "y17"),
    "leftArrow": ("x1", "y1", "r", "y2"),
    "leftArrowCallout": ("x2", "t", "r", "b"),
    "leftBrace": ("il", "it", "r", "ib"),
    "leftBracket": ("il", "it", "r", "ib"),
    "leftCircularArrow": ("il", "it", "ir", "ib"),
    "leftRightArrow": ("x1", "y1", "x4", "y2"),
    "leftRightArrowCallout": ("x2", "t", "x3", "b"),
    "leftRightCircularArrow": ("il", "it", "ir", "ib"),
    "leftRightRibbon": ("x1", "ly1", "x4", "ry4"),
    "leftRightUpArrow": ("il", "y3", "ir", "y5"),
    "leftUpArrow": ("il", "y3", "x4", "y5"),
    "lightningBolt": ("x4", "y4", "x9", "y10"),
    "line": ("l", "t", "r", "b"),
    "lineInv": ("l", "t", "r", "b"),
    "mathDivide": ("x1", "y3", "x3", "y4"),
    "mathEqual": ("x1", "y1", "x2", "y4"),
    "mathMinus": ("x1", "y1", "x2", "y2"),
    "mathMultiply": ("xA", "yB", "xE", "yH"),
    "mathNotEqual": ("x1", "y1", "x8", "y4"),
    "mathPlus": ("x1", "y2", "x4", "y3"),
    "moon": ("g12w", "g15h", "g0w", "g16h"),
    "noSmoking": ("il", "it", "ir", "ib"),
    "nonIsoscelesTrapezoid": ("il", "it", "ir", "b"),
    "notchedRightArrow": ("x1", "y1", "x3", "y2"),
    "octagon": ("il", "il", "ir", "ib"),
    "parallelogram": ("il", "it", "ir", "ib"),
    "pentagon": ("x2", "it", "x3", "y2"),
    "pie": ("il", "ir", "it", "ib"),
    "pieWedge": ("x1", "y1", "r", "b"),
    "plaque": ("il", "il", "ir", "ib"),
    "plaqueTabs": ("dx", "dx", "x1", "y1"),
    "plus": ("il", "it", "ir", "ib"),
    "quadArrow": ("il", "y3", "ir", "y4"),
    "quadArrowCallout": ("x2", "y2", "x7", "y7"),
    "rect": ("l", "t", "r", "b"),
    "ribbon": ("x2", "y2", "x9", "b"),
    "ribbon2": ("x2", "t", "x9", "y2"),
    "rightArrow": ("l", "y1", "x2", "y2"),
    "rightArrowCallout": ("l", "t", "x2", "b"),
    "rightBrace": ("l", "it", "ir", "ib"),
    "rightBracket": ("l", "it", "ir", "ib"),
    "round1Rect": ("l", "t", "ir", "b"),
    "round2DiagRect": ("dx", "dx", "ir", "ib"),
    "round2SameRect": ("il", "tdx", "ir", "ib"),
    "roundRect": ("il", "il", "ir", "ib"),
    "rtTriangle": ("wd12", "it", "ir", "ib"),
    "smileyFace": ("il", "it", "ir", "ib"),
    "snip1Rect": ("l", "it", "ir", "b"),
    "snip2DiagRect": ("il", "il", "ir", "ib"),
    "snip2SameRect": ("il", "it", "ir", "ib"),
    "snipRoundRect": ("il", "il", "ir", "b"),
    "squareTabs": ("dx", "dx", "x1", "y1"),
    "star10": ("sx2", "sy2", "sx5", "sy3"),
    "star12": ("sx2", "sy2", "sx5", "sy5"),
    "star16": ("il", "it", "ir", "ib"),
    "star24": ("il", "it", "ir", "ib"),
    "star32": ("il", "it", "ir", "ib"),
    "star4": ("sx1", "sy1", "sx2", "sy2"),
    "star5": ("sx1", "sy1", "sx4", "sy3"),
    "star6": ("sx1", "sy1", "sx4", "sy2"),
    "star7": ("sx2", "sy1", "sx5", "sy3"),
    "star8": ("sx1", "sy1", "sx4", "sy4"),
    "straightConnector1": ("l", "t", "r", "b"),
    "stripedRightArrow": ("x4", "y1", "x6", "y2"),
    "sun": ("x9", "y9", "x8", "y8"),
    "swooshArrow": ("l", "t", "r", "b"),
    "teardrop": ("il", "it", "ir", "ib"),
    "trapezoid": ("il", "it", "ir", "b"),
    "triangle": ("x1", "vc", "x3", "b"),
    "upArrow": ("x1", "y1", "x2", "b"),
    "upArrowCallout": ("l", "y2", "r", "b"),
    "upDownArrow": ("x1", "y1", "x2", "y4"),
    "upDownArrowCallout": ("l", "y2", "r", "y3"),
    "uturnArrow": ("l", "t", "r", "b"),
    "verticalScroll": ("ch", "ch", "x6", "y4"),
    "wave": ("il", "it", "ir", "ib"),
    "wedgeEllipseCallout": ("il", "it", "ir", "ib"),
    "wedgeRectCallout": ("l", "t", "r", "b"),
    "wedgeRoundRectCallout": ("il", "il", "ir", "ib"),
}
# fmt: on
