"""What each code of the Microsoft symbol faces stands for in Unicode.

Generated by ``tools/derive_symbol_maps.py`` -- do not edit.  Symbol from Adobe's
Symbol Encoding to Unicode table, Wingdings, Wingdings 2, Wingdings 3 and Webdings
from the Unicode Consortium's proposal that encoded them (UTC L2/11-344), by
character name against Python 3.12's Unicode 15.0.0 database.  Facts about
the encodings: no glyph and no font file.  Read through
:mod:`ooxml_common.text.symbol_fonts`, which adds the drawing preferences.
"""

#: face (lower case) -> {code 0x20..0xFF: Unicode code point}.
MAPS: dict[str, dict[int, int]] = {
    'symbol': {
        0x20: 0x0020,  # space
        0x21: 0x0021,  # exclamation mark
        0x22: 0x2200,  # for all
        0x23: 0x0023,  # number sign
        0x24: 0x2203,  # there exists
        0x25: 0x0025,  # percent sign
        0x26: 0x0026,  # ampersand
        0x27: 0x220B,  # contains as member
        0x28: 0x0028,  # left parenthesis
        0x29: 0x0029,  # right parenthesis
        0x2A: 0x2217,  # asterisk operator
        0x2B: 0x002B,  # plus sign
        0x2C: 0x002C,  # comma
        0x2D: 0x2212,  # minus sign
        0x2E: 0x002E,  # full stop
        0x2F: 0x002F,  # solidus
        0x30: 0x0030,  # digit zero
        0x31: 0x0031,  # digit one
        0x32: 0x0032,  # digit two
        0x33: 0x0033,  # digit three
        0x34: 0x0034,  # digit four
        0x35: 0x0035,  # digit five
        0x36: 0x0036,  # digit six
        0x37: 0x0037,  # digit seven
        0x38: 0x0038,  # digit eight
        0x39: 0x0039,  # digit nine
        0x3A: 0x003A,  # colon
        0x3B: 0x003B,  # semicolon
        0x3C: 0x003C,  # less-than sign
        0x3D: 0x003D,  # equals sign
        0x3E: 0x003E,  # greater-than sign
        0x3F: 0x003F,  # question mark
        0x40: 0x2245,  # approximately equal to
        0x41: 0x0391,  # greek capital letter alpha
        0x42: 0x0392,  # greek capital letter beta
        0x43: 0x03A7,  # greek capital letter chi
        0x44: 0x0394,  # greek capital letter delta
        0x45: 0x0395,  # greek capital letter epsilon
        0x46: 0x03A6,  # greek capital letter phi
        0x47: 0x0393,  # greek capital letter gamma
        0x48: 0x0397,  # greek capital letter eta
        0x49: 0x0399,  # greek capital letter iota
        0x4A: 0x03D1,  # greek theta symbol
        0x4B: 0x039A,  # greek capital letter kappa
        0x4C: 0x039B,  # greek capital letter lamda
        0x4D: 0x039C,  # greek capital letter mu
        0x4E: 0x039D,  # greek capital letter nu
        0x4F: 0x039F,  # greek capital letter omicron
        0x50: 0x03A0,  # greek capital letter pi
        0x51: 0x0398,  # greek capital letter theta
        0x52: 0x03A1,  # greek capital letter rho
        0x53: 0x03A3,  # greek capital letter sigma
        0x54: 0x03A4,  # greek capital letter tau
        0x55: 0x03A5,  # greek capital letter upsilon
        0x56: 0x03C2,  # greek small letter final sigma
        0x57: 0x03A9,  # greek capital letter omega
        0x58: 0x039E,  # greek capital letter xi
        0x59: 0x03A8,  # greek capital letter psi
        0x5A: 0x0396,  # greek capital letter zeta
        0x5B: 0x005B,  # left square bracket
        0x5C: 0x2234,  # therefore
        0x5D: 0x005D,  # right square bracket
        0x5E: 0x22A5,  # up tack
        0x5F: 0x005F,  # low line
        0x61: 0x03B1,  # greek small letter alpha
        0x62: 0x03B2,  # greek small letter beta
        0x63: 0x03C7,  # greek small letter chi
        0x64: 0x03B4,  # greek small letter delta
        0x65: 0x03B5,  # greek small letter epsilon
        0x66: 0x03C6,  # greek small letter phi
        0x67: 0x03B3,  # greek small letter gamma
        0x68: 0x03B7,  # greek small letter eta
        0x69: 0x03B9,  # greek small letter iota
        0x6A: 0x03D5,  # greek phi symbol
        0x6B: 0x03BA,  # greek small letter kappa
        0x6C: 0x03BB,  # greek small letter lamda
        0x6D: 0x00B5,  # micro sign
        0x6E: 0x03BD,  # greek small letter nu
        0x6F: 0x03BF,  # greek small letter omicron
        0x70: 0x03C0,  # greek small letter pi
        0x71: 0x03B8,  # greek small letter theta
        0x72: 0x03C1,  # greek small letter rho
        0x73: 0x03C3,  # greek small letter sigma
        0x74: 0x03C4,  # greek small letter tau
        0x75: 0x03C5,  # greek small letter upsilon
        0x76: 0x03D6,  # greek pi symbol
        0x77: 0x03C9,  # greek small letter omega
        0x78: 0x03BE,  # greek small letter xi
        0x79: 0x03C8,  # greek small letter psi
        0x7A: 0x03B6,  # greek small letter zeta
        0x7B: 0x007B,  # left curly bracket
        0x7C: 0x007C,  # vertical line
        0x7D: 0x007D,  # right curly bracket
        0x7E: 0x223C,  # tilde operator
        0xA0: 0x20AC,  # euro sign
        0xA1: 0x03D2,  # greek upsilon with hook symbol
        0xA2: 0x2032,  # prime
        0xA3: 0x2264,  # less-than or equal to
        0xA4: 0x2044,  # fraction slash
        0xA5: 0x221E,  # infinity
        0xA6: 0x0192,  # latin small letter f with hook
        0xA7: 0x2663,  # black club suit
        0xA8: 0x2666,  # black diamond suit
        0xA9: 0x2665,  # black heart suit
        0xAA: 0x2660,  # black spade suit
        0xAB: 0x2194,  # left right arrow
        0xAC: 0x2190,  # leftwards arrow
        0xAD: 0x2191,  # upwards arrow
        0xAE: 0x2192,  # rightwards arrow
        0xAF: 0x2193,  # downwards arrow
        0xB0: 0x00B0,  # degree sign
        0xB1: 0x00B1,  # plus-minus sign
        0xB2: 0x2033,  # double prime
        0xB3: 0x2265,  # greater-than or equal to
        0xB4: 0x00D7,  # multiplication sign
        0xB5: 0x221D,  # proportional to
        0xB6: 0x2202,  # partial differential
        0xB7: 0x2022,  # bullet
        0xB8: 0x00F7,  # division sign
        0xB9: 0x2260,  # not equal to
        0xBA: 0x2261,  # identical to
        0xBB: 0x2248,  # almost equal to
        0xBC: 0x2026,  # horizontal ellipsis
        0xBF: 0x21B5,  # downwards arrow with corner leftwards
        0xC0: 0x2135,  # alef symbol
        0xC1: 0x2111,  # black-letter capital i
        0xC2: 0x211C,  # black-letter capital r
        0xC3: 0x2118,  # script capital p
        0xC4: 0x2297,  # circled times
        0xC5: 0x2295,  # circled plus
        0xC6: 0x2205,  # empty set
        0xC7: 0x2229,  # intersection
        0xC8: 0x222A,  # union
        0xC9: 0x2283,  # superset of
        0xCA: 0x2287,  # superset of or equal to
        0xCB: 0x2284,  # not a subset of
        0xCC: 0x2282,  # subset of
        0xCD: 0x2286,  # subset of or equal to
        0xCE: 0x2208,  # element of
        0xCF: 0x2209,  # not an element of
        0xD0: 0x2220,  # angle
        0xD1: 0x2207,  # nabla
        0xD2: 0x00AE,  # registered sign
        0xD3: 0x00A9,  # copyright sign
        0xD4: 0x2122,  # trade mark sign
        0xD5: 0x220F,  # n-ary product
        0xD6: 0x221A,  # square root
        0xD7: 0x22C5,  # dot operator
        0xD8: 0x00AC,  # not sign
        0xD9: 0x2227,  # logical and
        0xDA: 0x2228,  # logical or
        0xDB: 0x21D4,  # left right double arrow
        0xDC: 0x21D0,  # leftwards double arrow
        0xDD: 0x21D1,  # upwards double arrow
        0xDE: 0x21D2,  # rightwards double arrow
        0xDF: 0x21D3,  # downwards double arrow
        0xE0: 0x25CA,  # lozenge
        0xE1: 0x2329,  # left-pointing angle bracket
        0xE2: 0x00AE,  # registered sign
        0xE3: 0x00A9,  # copyright sign
        0xE4: 0x2122,  # trade mark sign
        0xE5: 0x2211,  # n-ary summation
        0xF1: 0x232A,  # right-pointing angle bracket
        0xF2: 0x222B,  # integral
        0xF3: 0x2320,  # top half integral
        0xF5: 0x2321,  # bottom half integral
    },
    'wingdings': {
        0x21: 0x1F589,  # lower left pencil
        0x22: 0x2702,  # black scissors
        0x23: 0x2701,  # upper blade scissors
        0x24: 0x1F453,  # eyeglasses
        0x25: 0x1F56D,  # ringing bell
        0x26: 0x1F4D6,  # open book
        0x27: 0x1F56F,  # candle
        0x28: 0x1F57F,  # black touchtone telephone
        0x29: 0x2706,  # telephone location sign
        0x2A: 0x1F582,  # back of envelope
        0x2B: 0x1F583,  # stamped envelope
        0x2C: 0x1F4EA,  # closed mailbox with lowered flag
        0x2D: 0x1F4EB,  # closed mailbox with raised flag
        0x30: 0x1F5C0,  # folder
        0x32: 0x1F5CE,  # document
        0x33: 0x1F5CF,  # page
        0x34: 0x1F5D0,  # pages
        0x35: 0x1F5C4,  # file cabinet
        0x36: 0x23F3,  # hourglass with flowing sand
        0x37: 0x1F5AE,  # wired keyboard
        0x38: 0x1F5B0,  # two button mouse
        0x39: 0x1F5B2,  # trackball
        0x3A: 0x1F5B3,  # old personal computer
        0x3B: 0x1F5B4,  # hard disk
        0x3C: 0x1F5AB,  # white hard shell floppy disk
        0x3D: 0x1F5AC,  # soft shell floppy disk
        0x3E: 0x2707,  # tape drive
        0x3F: 0x270D,  # writing hand
        0x40: 0x1F58E,  # left writing hand
        0x41: 0x270C,  # victory hand
        0x42: 0x1F58F,  # turned ok hand sign
        0x43: 0x1F44D,  # thumbs up sign
        0x44: 0x1F44E,  # thumbs down sign
        0x45: 0x261C,  # white left pointing index
        0x46: 0x261E,  # white right pointing index
        0x47: 0x261D,  # white up pointing index
        0x48: 0x1F597,  # white down pointing left hand index
        0x49: 0x1F590,  # raised hand with fingers splayed
        0x4A: 0x263A,  # white smiling face
        0x4B: 0x1F610,  # neutral face
        0x4C: 0x2639,  # white frowning face
        0x4D: 0x1F4A3,  # bomb
        0x4E: 0x1F571,  # black skull and crossbones
        0x4F: 0x1F3F3,  # waving white flag
        0x51: 0x2708,  # airplane
        0x52: 0x263C,  # white sun with rays
        0x53: 0x1F322,  # black droplet
        0x54: 0x2744,  # snowflake
        0x55: 0x1F546,  # white latin cross
        0x56: 0x271E,  # shadowed white latin cross
        0x57: 0x1F548,  # celtic cross
        0x58: 0x2720,  # maltese cross
        0x59: 0x2721,  # star of david
        0x5A: 0x262A,  # star and crescent
        0x5B: 0x262F,  # yin yang
        0x5C: 0x1F549,  # om symbol
        0x5D: 0x2638,  # wheel of dharma
        0x5E: 0x2648,  # aries
        0x5F: 0x2649,  # taurus
        0x60: 0x264A,  # gemini
        0x61: 0x264B,  # cancer
        0x62: 0x264C,  # leo
        0x63: 0x264D,  # virgo
        0x64: 0x264E,  # libra
        0x65: 0x264F,  # scorpius
        0x66: 0x2650,  # sagittarius
        0x67: 0x2651,  # capricorn
        0x68: 0x2652,  # aquarius
        0x69: 0x2653,  # pisces
        0x6C: 0x26AB,  # medium black circle
        0x6D: 0x1F53E,  # lower right shadowed white circle
        0x6E: 0x25FC,  # black medium square
        0x6F: 0x1F78F,  # medium white square
        0x70: 0x1F790,  # bold white square
        0x71: 0x2751,  # lower right shadowed white square
        0x72: 0x2752,  # upper right shadowed white square
        0x73: 0x1F79F,  # black medium small lozenge
        0x74: 0x29EB,  # black lozenge
        0x75: 0x25C6,  # black diamond
        0x76: 0x2756,  # black diamond minus white x
        0x78: 0x2327,  # x in a rectangle box
        0x79: 0x2BB9,  # up arrowhead in a rectangle box
        0x7A: 0x2318,  # place of interest sign
        0x7B: 0x1F3F5,  # rosette
        0x7C: 0x1F3F6,  # black rosette
        0x7D: 0x1F676,  # sans-serif heavy double turned comma quotation mark ornament
        0x7E: 0x1F677,  # sans-serif heavy double comma quotation mark ornament
        0x80: 0x1F10B,  # dingbat circled sans-serif digit zero
        0x81: 0x2780,  # dingbat circled sans-serif digit one
        0x82: 0x2781,  # dingbat circled sans-serif digit two
        0x83: 0x2782,  # dingbat circled sans-serif digit three
        0x84: 0x2783,  # dingbat circled sans-serif digit four
        0x85: 0x2784,  # dingbat circled sans-serif digit five
        0x86: 0x2785,  # dingbat circled sans-serif digit six
        0x87: 0x2786,  # dingbat circled sans-serif digit seven
        0x88: 0x2787,  # dingbat circled sans-serif digit eight
        0x89: 0x2788,  # dingbat circled sans-serif digit nine
        0x8C: 0x278A,  # dingbat negative circled sans-serif digit one
        0x8D: 0x278B,  # dingbat negative circled sans-serif digit two
        0x8E: 0x278C,  # dingbat negative circled sans-serif digit three
        0x8F: 0x278D,  # dingbat negative circled sans-serif digit four
        0x90: 0x278E,  # dingbat negative circled sans-serif digit five
        0x91: 0x278F,  # dingbat negative circled sans-serif digit six
        0x92: 0x2790,  # dingbat negative circled sans-serif digit seven
        0x93: 0x2791,  # dingbat negative circled sans-serif digit eight
        0x94: 0x2792,  # dingbat negative circled sans-serif digit nine
        0x96: 0x1F662,  # north east pointing bud
        0x97: 0x1F660,  # north west pointing bud
        0x98: 0x1F661,  # south west pointing bud
        0x99: 0x1F663,  # south east pointing bud
        0x9A: 0x1F65E,  # heavy north east pointing vine leaf
        0x9B: 0x1F65C,  # heavy north west pointing vine leaf
        0x9C: 0x1F65D,  # heavy south west pointing vine leaf
        0x9D: 0x1F65F,  # heavy south east pointing vine leaf
        0x9E: 0x2219,  # bullet operator
        0x9F: 0x2022,  # bullet
        0xA0: 0x2B1D,  # black very small square
        0xA1: 0x2B58,  # heavy circle
        0xA2: 0x1F786,  # bold white circle
        0xA3: 0x1F788,  # very heavy white circle
        0xA4: 0x1F78A,  # white circle containing black small circle
        0xA5: 0x1F78B,  # round target
        0xA6: 0x1F53F,  # upper right shadowed white circle
        0xA7: 0x25AA,  # black small square
        0xA8: 0x1F78E,  # light white square
        0xA9: 0x1F7C1,  # medium three pointed black star
        0xAA: 0x1F7C5,  # medium four pointed black star
        0xAB: 0x2605,  # black star
        0xAC: 0x1F7CB,  # medium six pointed black star
        0xAD: 0x1F7CF,  # heavy eight pointed black star
        0xAE: 0x1F7D3,  # heavy twelve pointed black star
        0xAF: 0x1F7D1,  # heavy eight pointed pinwheel star
        0xB0: 0x2BD0,  # square position indicator
        0xB1: 0x2316,  # position indicator
        0xB2: 0x2BCE,  # white four pointed cusp
        0xB3: 0x2BCF,  # rotated white four pointed cusp
        0xB4: 0x2BD1,  # uncertainty sign
        0xB5: 0x272A,  # circled white star
        0xB6: 0x2730,  # shadowed white star
        0xB7: 0x1F550,  # clock face one oclock
        0xB8: 0x1F551,  # clock face two oclock
        0xB9: 0x1F552,  # clock face three oclock
        0xBA: 0x1F553,  # clock face four oclock
        0xBB: 0x1F554,  # clock face five oclock
        0xBC: 0x1F555,  # clock face six oclock
        0xBD: 0x1F556,  # clock face seven oclock
        0xBE: 0x1F557,  # clock face eight oclock
        0xBF: 0x1F558,  # clock face nine oclock
        0xC0: 0x1F559,  # clock face ten oclock
        0xC1: 0x1F55A,  # clock face eleven oclock
        0xC2: 0x1F55B,  # clock face twelve oclock
        0xC3: 0x2BB0,  # ribbon arrow down left
        0xC4: 0x2BB1,  # ribbon arrow down right
        0xC5: 0x2BB2,  # ribbon arrow up left
        0xC6: 0x2BB3,  # ribbon arrow up right
        0xC7: 0x2BB4,  # ribbon arrow left up
        0xC8: 0x2BB5,  # ribbon arrow right up
        0xC9: 0x2BB6,  # ribbon arrow left down
        0xCA: 0x2BB7,  # ribbon arrow right down
        0xCB: 0x1F66A,  # solid quilt square ornament
        0xCC: 0x1F66B,  # solid quilt square ornament in black square
        0xD5: 0x232B,  # erase to the left
        0xD6: 0x2326,  # erase to the right
        0xD7: 0x2B98,  # three-d top-lighted leftwards equilateral arrowhead
        0xD8: 0x2B9A,  # three-d top-lighted rightwards equilateral arrowhead
        0xD9: 0x2B99,  # three-d right-lighted upwards equilateral arrowhead
        0xDA: 0x2B9B,  # three-d left-lighted downwards equilateral arrowhead
        0xDB: 0x2B88,  # leftwards black circled white arrow
        0xDC: 0x2B8A,  # rightwards black circled white arrow
        0xDD: 0x2B89,  # upwards black circled white arrow
        0xDE: 0x2B8B,  # downwards black circled white arrow
        0xDF: 0x1F868,  # wide-headed leftwards barb arrow
        0xE0: 0x1F86A,  # wide-headed rightwards barb arrow
        0xE1: 0x1F869,  # wide-headed upwards barb arrow
        0xE2: 0x1F86B,  # wide-headed downwards barb arrow
        0xE3: 0x1F86C,  # wide-headed north west barb arrow
        0xE4: 0x1F86D,  # wide-headed north east barb arrow
        0xE5: 0x1F86F,  # wide-headed south west barb arrow
        0xE6: 0x1F86E,  # wide-headed south east barb arrow
        0xE7: 0x1F878,  # wide-headed leftwards heavy barb arrow
        0xE8: 0x1F87A,  # wide-headed rightwards heavy barb arrow
        0xE9: 0x1F879,  # wide-headed upwards heavy barb arrow
        0xEA: 0x1F87B,  # wide-headed downwards heavy barb arrow
        0xEB: 0x1F87C,  # wide-headed north west heavy barb arrow
        0xEC: 0x1F87D,  # wide-headed north east heavy barb arrow
        0xED: 0x1F87F,  # wide-headed south west heavy barb arrow
        0xEE: 0x1F87E,  # wide-headed south east heavy barb arrow
        0xEF: 0x21E6,  # leftwards white arrow
        0xF0: 0x21E8,  # rightwards white arrow
        0xF1: 0x21E7,  # upwards white arrow
        0xF2: 0x21E9,  # downwards white arrow
        0xF3: 0x2B04,  # left right white arrow
        0xF4: 0x21F3,  # up down white arrow
        0xF5: 0x2B01,  # north west white arrow
        0xF6: 0x2B00,  # north east white arrow
        0xF7: 0x2B03,  # south west white arrow
        0xF8: 0x2B02,  # south east white arrow
        0xFB: 0x1F5F6,  # ballot bold script x
        0xFC: 0x2713,  # check mark
        0xFD: 0x1F5F7,  # ballot box with bold script x
        0xFE: 0x1F5F9,  # ballot box with bold check
    },
    'wingdings 2': {
        0x21: 0x1F58A,  # lower left ballpoint pen
        0x22: 0x1F58B,  # lower left fountain pen
        0x23: 0x1F58C,  # lower left paintbrush
        0x24: 0x1F58D,  # lower left crayon
        0x25: 0x2704,  # white scissors
        0x26: 0x2700,  # black safety scissors
        0x27: 0x1F57E,  # white touchtone telephone
        0x28: 0x1F57D,  # right hand telephone receiver
        0x29: 0x1F5C5,  # empty note
        0x2A: 0x1F5C6,  # empty note page
        0x2B: 0x1F5C7,  # empty note pad
        0x2C: 0x1F5C8,  # note
        0x2D: 0x1F5C9,  # note page
        0x2E: 0x1F5CA,  # note pad
        0x2F: 0x1F5CB,  # empty document
        0x30: 0x1F5CC,  # empty page
        0x31: 0x1F5CD,  # empty pages
        0x32: 0x1F4CB,  # clipboard
        0x33: 0x1F5D1,  # wastebasket
        0x35: 0x1F5B5,  # screen
        0x36: 0x1F5B6,  # printer icon
        0x38: 0x1F5B8,  # optical disc icon
        0x39: 0x1F5AD,  # tape cartridge
        0x3A: 0x1F5AF,  # one button mouse
        0x3B: 0x1F5B1,  # three button mouse
        0x3C: 0x1F592,  # reversed thumbs up sign
        0x3D: 0x1F593,  # reversed thumbs down sign
        0x3E: 0x1F598,  # sideways white left pointing index
        0x3F: 0x1F599,  # sideways white right pointing index
        0x40: 0x1F59A,  # sideways black left pointing index
        0x41: 0x1F59B,  # sideways black right pointing index
        0x42: 0x1F448,  # white left pointing backhand index
        0x43: 0x1F449,  # white right pointing backhand index
        0x44: 0x1F59C,  # black left pointing backhand index
        0x45: 0x1F59D,  # black right pointing backhand index
        0x46: 0x1F59E,  # sideways white up pointing index
        0x47: 0x1F59F,  # sideways white down pointing index
        0x48: 0x1F5A0,  # sideways black up pointing index
        0x49: 0x1F5A1,  # sideways black down pointing index
        0x4A: 0x1F446,  # white up pointing backhand index
        0x4B: 0x1F447,  # white down pointing backhand index
        0x4C: 0x1F5A2,  # black up pointing backhand index
        0x4D: 0x1F5A3,  # black down pointing backhand index
        0x4E: 0x1F591,  # reversed raised hand with fingers splayed
        0x4F: 0x1F5F4,  # ballot script x
        0x50: 0x1F5F8,  # light check mark
        0x51: 0x1F5F5,  # ballot box with script x
        0x52: 0x2611,  # ballot box with check
        0x53: 0x2BBD,  # ballot box with light x
        0x54: 0x2612,  # ballot box with x
        0x55: 0x2BBE,  # circled x
        0x56: 0x2BBF,  # circled bold x
        0x58: 0x29B8,  # circled reverse solidus
        0x5D: 0x203D,  # interrobang
        0x5F: 0x1F67A,  # sans-serif interrobang ornament
        0x61: 0x1F666,  # heavy north east pointing bud
        0x62: 0x1F664,  # heavy north west pointing bud
        0x63: 0x1F665,  # heavy south west pointing bud
        0x64: 0x1F667,  # heavy south east pointing bud
        0x65: 0x1F65A,  # north east pointing vine leaf
        0x66: 0x1F658,  # north west pointing vine leaf
        0x67: 0x1F659,  # south west pointing vine leaf
        0x68: 0x1F65B,  # south east pointing vine leaf
        0x69: 0x24EA,  # circled digit zero
        0x6A: 0x2460,  # circled digit one
        0x6B: 0x2461,  # circled digit two
        0x6C: 0x2462,  # circled digit three
        0x6D: 0x2463,  # circled digit four
        0x6E: 0x2464,  # circled digit five
        0x6F: 0x2465,  # circled digit six
        0x70: 0x2466,  # circled digit seven
        0x71: 0x2467,  # circled digit eight
        0x72: 0x2468,  # circled digit nine
        0x74: 0x24FF,  # negative circled digit zero
        0x75: 0x2776,  # dingbat negative circled digit one
        0x76: 0x2777,  # dingbat negative circled digit two
        0x77: 0x2778,  # dingbat negative circled digit three
        0x78: 0x2779,  # dingbat negative circled digit four
        0x79: 0x277A,  # dingbat negative circled digit five
        0x7A: 0x277B,  # dingbat negative circled digit six
        0x7B: 0x277C,  # dingbat negative circled digit seven
        0x7C: 0x277D,  # dingbat negative circled digit eight
        0x7D: 0x277E,  # dingbat negative circled digit nine
        0x80: 0x2609,  # sun
        0x81: 0x1F315,  # full moon symbol
        0x82: 0x263D,  # first quarter moon
        0x83: 0x263E,  # last quarter moon
        0x84: 0x2E3F,  # capitulum
        0x85: 0x271D,  # latin cross
        0x86: 0x1F547,  # heavy latin cross
        0x87: 0x1F55C,  # clock face one-thirty
        0x88: 0x1F55D,  # clock face two-thirty
        0x89: 0x1F55E,  # clock face three-thirty
        0x8A: 0x1F55F,  # clock face four-thirty
        0x8B: 0x1F560,  # clock face five-thirty
        0x8C: 0x1F561,  # clock face six-thirty
        0x8D: 0x1F562,  # clock face seven-thirty
        0x8E: 0x1F563,  # clock face eight-thirty
        0x8F: 0x1F564,  # clock face nine-thirty
        0x90: 0x1F565,  # clock face ten-thirty
        0x91: 0x1F566,  # clock face eleven-thirty
        0x92: 0x1F567,  # clock face twelve-thirty
        0x93: 0x1F668,  # hollow quilt square ornament
        0x94: 0x1F669,  # hollow quilt square ornament in black square
        0x95: 0x22C5,  # dot operator
        0x96: 0x1F784,  # black slightly small circle
        0x97: 0x2981,  # z notation spot
        0x98: 0x25CF,  # black circle
        0x99: 0x25CB,  # white circle
        0x9A: 0x26AA,  # medium white circle
        0x9B: 0x1F787,  # heavy white circle
        0x9C: 0x1F789,  # extremely heavy white circle
        0x9D: 0x2299,  # circled dot operator
        0x9E: 0x29BF,  # circled bullet
        0x9F: 0x1F78C,  # black tiny square
        0xA0: 0x1F78D,  # black slightly small square
        0xA1: 0x25FE,  # black medium small square
        0xA2: 0x25A0,  # black square
        0xA3: 0x25A1,  # white square
        0xA4: 0x1F791,  # heavy white square
        0xA5: 0x1F792,  # very heavy white square
        0xA6: 0x1F793,  # extremely heavy white square
        0xA7: 0x1F794,  # white square containing black very small square
        0xA8: 0x25A3,  # white square containing black small square
        0xA9: 0x1F795,  # white square containing black medium square
        0xAA: 0x1F796,  # square target
        0xAB: 0x1F797,  # black tiny diamond
        0xAC: 0x1F798,  # black very small diamond
        0xAD: 0x2B29,  # black small diamond
        0xAE: 0x2B25,  # black medium diamond
        0xAF: 0x25C7,  # white diamond
        0xB0: 0x1F79A,  # white diamond containing black very small diamond
        0xB1: 0x25C8,  # white diamond containing black small diamond
        0xB2: 0x1F79B,  # white diamond containing black medium diamond
        0xB3: 0x1F79C,  # diamond target
        0xB4: 0x1F79D,  # black tiny lozenge
        0xB5: 0x1F79E,  # black very small lozenge
        0xB6: 0x2B2A,  # black small lozenge
        0xB7: 0x2B27,  # black medium lozenge
        0xB8: 0x25CA,  # lozenge
        0xB9: 0x1F7A0,  # white lozenge containing black small lozenge
        0xBA: 0x25D6,  # left half black circle
        0xBB: 0x25D7,  # right half black circle
        0xBC: 0x2BCA,  # top half black circle
        0xBD: 0x2BCB,  # bottom half black circle
        0xC0: 0x2B1F,  # black pentagon
        0xC1: 0x2BC2,  # turned black pentagon
        0xC2: 0x2B23,  # horizontal black hexagon
        0xC3: 0x2B22,  # black hexagon
        0xC4: 0x2BC3,  # horizontal black octagon
        0xC5: 0x2BC4,  # black octagon
        0xC6: 0x1F7A1,  # thin greek cross
        0xC7: 0x1F7A2,  # light greek cross
        0xC8: 0x1F7A3,  # medium greek cross
        0xC9: 0x1F7A4,  # bold greek cross
        0xCA: 0x1F7A5,  # very bold greek cross
        0xCB: 0x1F7A6,  # very heavy greek cross
        0xCC: 0x1F7A7,  # extremely heavy greek cross
        0xCD: 0x1F7A8,  # thin saltire
        0xCE: 0x1F7A9,  # light saltire
        0xCF: 0x1F7AA,  # medium saltire
        0xD0: 0x1F7AB,  # bold saltire
        0xD1: 0x1F7AC,  # heavy saltire
        0xD2: 0x1F7AD,  # very heavy saltire
        0xD3: 0x1F7AE,  # extremely heavy saltire
        0xD4: 0x1F7AF,  # light five spoked asterisk
        0xD5: 0x1F7B0,  # medium five spoked asterisk
        0xD6: 0x1F7B1,  # bold five spoked asterisk
        0xD7: 0x1F7B2,  # heavy five spoked asterisk
        0xD8: 0x1F7B3,  # very heavy five spoked asterisk
        0xD9: 0x1F7B4,  # extremely heavy five spoked asterisk
        0xDA: 0x1F7B5,  # light six spoked asterisk
        0xDB: 0x1F7B6,  # medium six spoked asterisk
        0xDC: 0x1F7B7,  # bold six spoked asterisk
        0xDD: 0x1F7B8,  # heavy six spoked asterisk
        0xDE: 0x1F7B9,  # very heavy six spoked asterisk
        0xDF: 0x1F7BA,  # extremely heavy six spoked asterisk
        0xE0: 0x1F7BB,  # light eight spoked asterisk
        0xE1: 0x1F7BC,  # medium eight spoked asterisk
        0xE2: 0x1F7BD,  # bold eight spoked asterisk
        0xE3: 0x1F7BE,  # heavy eight spoked asterisk
        0xE4: 0x1F7BF,  # very heavy eight spoked asterisk
        0xE5: 0x1F7C0,  # light three pointed black star
        0xE6: 0x1F7C2,  # three pointed black star
        0xE7: 0x1F7C4,  # light four pointed black star
        0xE8: 0x1F7C6,  # four pointed black star
        0xE9: 0x1F7C9,  # light five pointed black star
        0xEA: 0x1F7CA,  # heavy five pointed black star
        0xEB: 0x2736,  # six pointed black star
        0xEC: 0x1F7CC,  # heavy six pointed black star
        0xED: 0x1F7CE,  # medium eight pointed black star
        0xEE: 0x1F7D0,  # very heavy eight pointed black star
        0xEF: 0x1F7D2,  # light twelve pointed black star
        0xF0: 0x2739,  # twelve pointed black star
        0xF1: 0x1F7C3,  # medium three pointed pinwheel star
        0xF2: 0x1F7C7,  # medium four pointed pinwheel star
        0xF3: 0x272F,  # pinwheel star
        0xF4: 0x1F7CD,  # six pointed pinwheel star
        0xF5: 0x1F7D4,  # heavy twelve pointed pinwheel star
        0xF6: 0x2BCC,  # light four pointed black cusp
        0xF7: 0x2BCD,  # rotated light four pointed black cusp
        0xF8: 0x203B,  # reference mark
        0xF9: 0x2042,  # asterism
    },
    'wingdings 3': {
        0x21: 0x2B60,  # leftwards triangle-headed arrow
        0x22: 0x2B62,  # rightwards triangle-headed arrow
        0x23: 0x2B61,  # upwards triangle-headed arrow
        0x24: 0x2B63,  # downwards triangle-headed arrow
        0x25: 0x2B66,  # north west triangle-headed arrow
        0x26: 0x2B67,  # north east triangle-headed arrow
        0x27: 0x2B69,  # south west triangle-headed arrow
        0x28: 0x2B68,  # south east triangle-headed arrow
        0x29: 0x2B70,  # leftwards triangle-headed arrow to bar
        0x2A: 0x2B72,  # rightwards triangle-headed arrow to bar
        0x2B: 0x2B71,  # upwards triangle-headed arrow to bar
        0x2C: 0x2B73,  # downwards triangle-headed arrow to bar
        0x2D: 0x2B76,  # north west triangle-headed arrow to bar
        0x2E: 0x2B78,  # south east triangle-headed arrow to bar
        0x2F: 0x2B7B,  # upwards triangle-headed arrow with double horizontal stroke
        0x30: 0x2B7D,  # downwards triangle-headed arrow with double horizontal stroke
        0x31: 0x2B64,  # left right triangle-headed arrow
        0x32: 0x2B65,  # up down triangle-headed arrow
        0x33: 0x2B6A,  # leftwards triangle-headed dashed arrow
        0x34: 0x2B6C,  # rightwards triangle-headed dashed arrow
        0x35: 0x2B6B,  # upwards triangle-headed dashed arrow
        0x36: 0x2B6D,  # downwards triangle-headed dashed arrow
        0x37: 0x2B4D,  # downwards triangle-headed zigzag arrow
        0x38: 0x2BA0,  # downwards triangle-headed arrow with long tip leftwards
        0x39: 0x2BA1,  # downwards triangle-headed arrow with long tip rightwards
        0x3A: 0x2BA2,  # upwards triangle-headed arrow with long tip leftwards
        0x3B: 0x2BA3,  # upwards triangle-headed arrow with long tip rightwards
        0x3C: 0x2BA4,  # leftwards triangle-headed arrow with long tip upwards
        0x3D: 0x2BA5,  # rightwards triangle-headed arrow with long tip upwards
        0x3E: 0x2BA6,  # leftwards triangle-headed arrow with long tip downwards
        0x3F: 0x2BA7,  # rightwards triangle-headed arrow with long tip downwards
        0x40: 0x2B90,  # return left
        0x41: 0x2B91,  # return right
        0x42: 0x2B92,  # newline left
        0x43: 0x2B93,  # newline right
        0x44: 0x2B80,  # leftwards triangle-headed arrow over rightwards triangle-headed arrow
        0x45: 0x2B83,  # downwards triangle-headed arrow leftwards of upwards triangle-headed arrow
        0x46: 0x2B7E,  # horizontal tab key
        0x47: 0x2B7F,  # vertical tab key
        0x48: 0x2B84,  # leftwards triangle-headed paired arrows
        0x49: 0x2B86,  # rightwards triangle-headed paired arrows
        0x4A: 0x2B85,  # upwards triangle-headed paired arrows
        0x4B: 0x2B87,  # downwards triangle-headed paired arrows
        0x4C: 0x2B8F,  # anticlockwise triangle-headed top u-shaped arrow
        0x4D: 0x2B8D,  # anticlockwise triangle-headed bottom u-shaped arrow
        0x4E: 0x2B8E,  # anticlockwise triangle-headed left u-shaped arrow
        0x4F: 0x2B8C,  # anticlockwise triangle-headed right u-shaped arrow
        0x50: 0x2B6E,  # clockwise triangle-headed open circle arrow
        0x51: 0x2B6F,  # anticlockwise triangle-headed open circle arrow
        0x52: 0x238B,  # broken circle with northwest arrow
        0x53: 0x2324,  # up arrowhead between two horizontal bars
        0x54: 0x2303,  # up arrowhead
        0x55: 0x2325,  # option key
        0x56: 0x2423,  # open box
        0x57: 0x237D,  # shouldered open box
        0x5A: 0x1F8A0,  # leftwards bottom-shaded white arrow
        0x5B: 0x1F8A1,  # rightwards bottom shaded white arrow
        0x5C: 0x1F8A2,  # leftwards top shaded white arrow
        0x5D: 0x1F8A3,  # rightwards top shaded white arrow
        0x5E: 0x1F8A4,  # leftwards left-shaded white arrow
        0x5F: 0x1F8A5,  # rightwards right-shaded white arrow
        0x60: 0x1F8A6,  # leftwards right-shaded white arrow
        0x61: 0x1F8A7,  # rightwards left-shaded white arrow
        0x62: 0x1F8A8,  # leftwards back-tilted shadowed white arrow
        0x63: 0x1F8A9,  # rightwards back-tilted shadowed white arrow
        0x64: 0x1F8AA,  # leftwards front-tilted shadowed white arrow
        0x65: 0x1F8AB,  # rightwards front-tilted shadowed white arrow
        0x66: 0x1F850,  # leftwards sans-serif arrow
        0x67: 0x1F852,  # rightwards sans-serif arrow
        0x68: 0x1F851,  # upwards sans-serif arrow
        0x69: 0x1F853,  # downwards sans-serif arrow
        0x6A: 0x1F854,  # north west sans-serif arrow
        0x6B: 0x1F855,  # north east sans-serif arrow
        0x6C: 0x1F857,  # south west sans-serif arrow
        0x6D: 0x1F856,  # south east sans-serif arrow
        0x6E: 0x1F858,  # left right sans-serif arrow
        0x6F: 0x1F859,  # up down sans-serif arrow
        0x70: 0x25B2,  # black up-pointing triangle
        0x71: 0x25BC,  # black down-pointing triangle
        0x72: 0x25B3,  # white up-pointing triangle
        0x73: 0x25BD,  # white down-pointing triangle
        0x74: 0x25C0,  # black left-pointing triangle
        0x75: 0x25B6,  # black right-pointing triangle
        0x76: 0x25C1,  # white left-pointing triangle
        0x77: 0x25B7,  # white right-pointing triangle
        0x78: 0x25E3,  # black lower left triangle
        0x79: 0x25E2,  # black lower right triangle
        0x7A: 0x25E4,  # black upper left triangle
        0x7B: 0x25E5,  # black upper right triangle
        0x7C: 0x1F780,  # black left-pointing isosceles right triangle
        0x7D: 0x1F782,  # black right-pointing isosceles right triangle
        0x7E: 0x1F781,  # black up-pointing isosceles right triangle
        0x80: 0x1F783,  # black down-pointing isosceles right triangle
        0x85: 0x2B9C,  # black leftwards equilateral arrowhead
        0x86: 0x2B9E,  # black rightwards equilateral arrowhead
        0x87: 0x2B9D,  # black upwards equilateral arrowhead
        0x88: 0x2B9F,  # black downwards equilateral arrowhead
        0x89: 0x1F810,  # leftwards arrow with small equilateral arrowhead
        0x8A: 0x1F812,  # rightwards arrow with small equilateral arrowhead
        0x8B: 0x1F811,  # upwards arrow with small equilateral arrowhead
        0x8C: 0x1F813,  # downwards arrow with small equilateral arrowhead
        0x8D: 0x1F814,  # leftwards arrow with equilateral arrowhead
        0x8E: 0x1F816,  # rightwards arrow with equilateral arrowhead
        0x8F: 0x1F815,  # upwards arrow with equilateral arrowhead
        0x90: 0x1F817,  # downwards arrow with equilateral arrowhead
        0x91: 0x1F818,  # heavy leftwards arrow with equilateral arrowhead
        0x92: 0x1F81A,  # heavy rightwards arrow with equilateral arrowhead
        0x93: 0x1F819,  # heavy upwards arrow with equilateral arrowhead
        0x94: 0x1F81B,  # heavy downwards arrow with equilateral arrowhead
        0x95: 0x1F81C,  # heavy leftwards arrow with large equilateral arrowhead
        0x96: 0x1F81E,  # heavy rightwards arrow with large equilateral arrowhead
        0x97: 0x1F81D,  # heavy upwards arrow with large equilateral arrowhead
        0x98: 0x1F81F,  # heavy downwards arrow with large equilateral arrowhead
        0x99: 0x1F800,  # leftwards arrow with small triangle arrowhead
        0x9A: 0x1F802,  # rightwards arrow with small triangle arrowhead
        0x9B: 0x1F801,  # upwards arrow with small triangle arrowhead
        0x9C: 0x1F803,  # downwards arrow with small triangle arrowhead
        0x9D: 0x1F804,  # leftwards arrow with medium triangle arrowhead
        0x9E: 0x1F806,  # rightwards arrow with medium triangle arrowhead
        0x9F: 0x1F805,  # upwards arrow with medium triangle arrowhead
        0xA0: 0x1F807,  # downwards arrow with medium triangle arrowhead
        0xA1: 0x1F808,  # leftwards arrow with large triangle arrowhead
        0xA2: 0x1F80A,  # rightwards arrow with large triangle arrowhead
        0xA3: 0x1F809,  # upwards arrow with large triangle arrowhead
        0xA4: 0x1F80B,  # downwards arrow with large triangle arrowhead
        0xA5: 0x1F820,  # leftwards triangle-headed arrow with narrow shaft
        0xA6: 0x1F822,  # rightwards triangle-headed arrow with narrow shaft
        0xA7: 0x1F824,  # leftwards triangle-headed arrow with medium shaft
        0xA8: 0x1F826,  # rightwards triangle-headed arrow with medium shaft
        0xA9: 0x1F828,  # leftwards triangle-headed arrow with bold shaft
        0xAA: 0x1F82A,  # rightwards triangle-headed arrow with bold shaft
        0xAB: 0x1F82C,  # leftwards triangle-headed arrow with heavy shaft
        0xAC: 0x1F89C,  # heavy arrow shaft width one
        0xAD: 0x1F89D,  # heavy arrow shaft width two thirds
        0xAE: 0x1F89E,  # heavy arrow shaft width one half
        0xAF: 0x1F89F,  # heavy arrow shaft width one third
        0xB0: 0x1F82E,  # rightwards triangle-headed arrow with heavy shaft
        0xB1: 0x1F830,  # leftwards triangle-headed arrow with very heavy shaft
        0xB2: 0x1F832,  # rightwards triangle-headed arrow with very heavy shaft
        0xB3: 0x1F834,  # leftwards finger-post arrow
        0xB4: 0x1F836,  # rightwards finger-post arrow
        0xB5: 0x1F838,  # leftwards squared arrow
        0xB6: 0x1F83A,  # rightwards squared arrow
        0xB7: 0x1F839,  # upwards squared arrow
        0xB8: 0x1F83B,  # downwards squared arrow
        0xB9: 0x1F898,  # leftwards arrow with notched tail
        0xBA: 0x1F89A,  # rightwards arrow with notched tail
        0xBB: 0x1F899,  # upwards arrow with notched tail
        0xBC: 0x1F89B,  # downwards arrow with notched tail
        0xBD: 0x1F83C,  # leftwards compressed arrow
        0xBE: 0x1F83E,  # rightwards compressed arrow
        0xBF: 0x1F83D,  # upwards compressed arrow
        0xC0: 0x1F83F,  # downwards compressed arrow
        0xC1: 0x1F840,  # leftwards heavy compressed arrow
        0xC2: 0x1F842,  # rightwards heavy compressed arrow
        0xC3: 0x1F841,  # upwards heavy compressed arrow
        0xC4: 0x1F843,  # downwards heavy compressed arrow
        0xC5: 0x1F844,  # leftwards heavy arrow
        0xC6: 0x1F846,  # rightwards heavy arrow
        0xC7: 0x1F845,  # upwards heavy arrow
        0xC8: 0x1F847,  # downwards heavy arrow
        0xC9: 0x2BA8,  # black curved downwards and leftwards arrow
        0xCA: 0x2BA9,  # black curved downwards and rightwards arrow
        0xCB: 0x2BAA,  # black curved upwards and leftwards arrow
        0xCC: 0x2BAB,  # black curved upwards and rightwards arrow
        0xCD: 0x2BAC,  # black curved leftwards and upwards arrow
        0xCE: 0x2BAD,  # black curved rightwards and upwards arrow
        0xCF: 0x2BAE,  # black curved leftwards and downwards arrow
        0xD0: 0x2BAF,  # black curved rightwards and downwards arrow
        0xD1: 0x1F860,  # wide-headed leftwards light barb arrow
        0xD2: 0x1F862,  # wide-headed rightwards light barb arrow
        0xD3: 0x1F861,  # wide-headed upwards light barb arrow
        0xD4: 0x1F863,  # wide-headed downwards light barb arrow
        0xD5: 0x1F864,  # wide-headed north west light barb arrow
        0xD6: 0x1F865,  # wide-headed north east light barb arrow
        0xD7: 0x1F867,  # wide-headed south west light barb arrow
        0xD8: 0x1F866,  # wide-headed south east light barb arrow
        0xD9: 0x1F870,  # wide-headed leftwards medium barb arrow
        0xDA: 0x1F872,  # wide-headed rightwards medium barb arrow
        0xDB: 0x1F871,  # wide-headed upwards medium barb arrow
        0xDC: 0x1F873,  # wide-headed downwards medium barb arrow
        0xDD: 0x1F874,  # wide-headed north west medium barb arrow
        0xDE: 0x1F875,  # wide-headed north east medium barb arrow
        0xDF: 0x1F877,  # wide-headed south west medium barb arrow
        0xE0: 0x1F876,  # wide-headed south east medium barb arrow
        0xE1: 0x1F880,  # wide-headed leftwards very heavy barb arrow
        0xE2: 0x1F882,  # wide-headed rightwards very heavy barb arrow
        0xE3: 0x1F881,  # wide-headed upwards very heavy barb arrow
        0xE4: 0x1F883,  # wide-headed downwards very heavy barb arrow
        0xE5: 0x1F884,  # wide-headed north west very heavy barb arrow
        0xE6: 0x1F885,  # wide-headed north east very heavy barb arrow
        0xE7: 0x1F887,  # wide-headed south west very heavy barb arrow
        0xE8: 0x1F886,  # wide-headed south east very heavy barb arrow
        0xE9: 0x1F890,  # leftwards triangle arrowhead
        0xEA: 0x1F892,  # rightwards triangle arrowhead
        0xEB: 0x1F891,  # upwards triangle arrowhead
        0xEC: 0x1F893,  # downwards triangle arrowhead
        0xED: 0x1F894,  # leftwards white arrow within triangle arrowhead
        0xEF: 0x1F895,  # upwards white arrow within triangle arrowhead
        0xF0: 0x1F897,  # downwards white arrow within triangle arrowhead
    },
    'webdings': {
        0x21: 0x1F577,  # spider
        0x22: 0x1F578,  # spider web
        0x23: 0x1F572,  # no piracy
        0x24: 0x1F576,  # dark sunglasses
        0x25: 0x1F3C6,  # trophy
        0x27: 0x1F587,  # linked paperclips
        0x28: 0x1F5E8,  # left speech bubble
        0x29: 0x1F5E9,  # right speech bubble
        0x2A: 0x1F5F0,  # mood bubble
        0x2B: 0x1F5F1,  # lightning mood bubble
        0x2C: 0x1F336,  # hot pepper
        0x2D: 0x1F397,  # reminder ribbon
        0x2E: 0x1F67E,  # checker board
        0x2F: 0x1F67C,  # very heavy solidus
        0x30: 0x1F5D5,  # minimize
        0x31: 0x1F5D6,  # maximize
        0x32: 0x1F5D7,  # overlap
        0x33: 0x23F4,  # black medium left-pointing triangle
        0x34: 0x23F5,  # black medium right-pointing triangle
        0x35: 0x23F6,  # black medium up-pointing triangle
        0x36: 0x23F7,  # black medium down-pointing triangle
        0x37: 0x23EA,  # black left-pointing double triangle
        0x38: 0x23E9,  # black right-pointing double triangle
        0x39: 0x23EE,  # black left-pointing double triangle with vertical bar
        0x3A: 0x23ED,  # black right-pointing double triangle with vertical bar
        0x3B: 0x23F8,  # double vertical bar
        0x3C: 0x23F9,  # black square for stop
        0x3D: 0x23FA,  # black circle for record
        0x3F: 0x1F5F3,  # ballot box with ballot
        0x43: 0x1F3D9,  # cityscape
        0x49: 0x1F3D6,  # beach with umbrella
        0x4A: 0x1F3DD,  # desert island
        0x4C: 0x1F50D,  # left-pointing magnifying glass
        0x4E: 0x1F441,  # eye
        0x4F: 0x1F442,  # ear
        0x51: 0x1F3D5,  # camping
        0x55: 0x1F56C,  # bullhorn with sound waves
        0x56: 0x1F56B,  # bullhorn
        0x57: 0x1F568,  # right speaker
        0x58: 0x1F509,  # speaker with one sound wave
        0x59: 0x1F394,  # heart with tip on the left
        0x5A: 0x1F395,  # bouquet of flowers
        0x5B: 0x1F5EC,  # left thought bubble
        0x5C: 0x1F67D,  # very heavy reverse solidus
        0x5D: 0x1F5ED,  # right thought bubble
        0x5E: 0x1F5EA,  # two speech bubbles
        0x5F: 0x1F5EB,  # three speech bubbles
        0x60: 0x2B94,  # four corner arrows circling anticlockwise
        0x61: 0x2714,  # heavy check mark
        0x62: 0x1F6B2,  # bicycle
        0x63: 0x2B1C,  # white large square
        0x64: 0x1F6E1,  # shield
        0x66: 0x1F6F1,  # oncoming fire engine
        0x67: 0x2B1B,  # black large square
        0x69: 0x1F6C8,  # circled information source
        0x6A: 0x1F6E9,  # small airplane
        0x6B: 0x1F6F0,  # satellite
        0x6C: 0x1F7C8,  # reverse light four pointed pinwheel star
        0x6D: 0x1F574,  # man in business suit levitating
        0x6E: 0x2B24,  # black large circle
        0x70: 0x1F694,  # oncoming police car
        0x71: 0x1F5D8,  # clockwise right and left semicircle arrows
        0x73: 0x2753,  # black question mark ornament
        0x76: 0x1F68D,  # oncoming bus
        0x77: 0x1F6A9,  # triangular flag on post
        0x79: 0x2296,  # circled minus
        0x7A: 0x1F6AD,  # no smoking symbol
        0x7B: 0x1F5EE,  # left anger bubble
        0x7C: 0x23D0,  # vertical line extension
        0x7D: 0x1F5EF,  # right anger bubble
        0x7E: 0x1F5F2,  # lightning mood
        0x80: 0x1F6B9,  # mens symbol
        0x81: 0x1F6BA,  # womens symbol
        0x86: 0x1F3CB,  # weight lifter
        0x87: 0x26F7,  # skier
        0x88: 0x1F3C2,  # snowboarder
        0x89: 0x1F3CC,  # golfer
        0x8A: 0x1F3CA,  # swimmer
        0x8B: 0x1F3C4,  # surfer
        0x8E: 0x1F698,  # oncoming automobile
        0x8F: 0x1F4C8,  # chart with upwards trend
        0x90: 0x1F6E2,  # oil drum
        0x93: 0x1F4B3,  # credit card
        0x94: 0x1F46A,  # family
        0x95: 0x1F5E1,  # dagger knife
        0x96: 0x1F5E2,  # lips
        0x98: 0x272F,  # pinwheel star
        0x9A: 0x1F585,  # flying envelope
        0x9B: 0x1F583,  # stamped envelope
        0x9C: 0x1F586,  # pen over stamped envelope
        0x9D: 0x1F5B9,  # document with text
        0x9E: 0x1F5BA,  # document with text and picture
        0x9F: 0x1F5BB,  # document with picture
        0xA0: 0x1F575,  # sleuth or spy
        0xA1: 0x1F570,  # mantelpiece clock
        0xA3: 0x1F5BE,  # frame with an x
        0xA8: 0x1F4DA,  # books
        0xA9: 0x1F5DE,  # rolled-up newspaper
        0xAB: 0x1F5C3,  # card file box
        0xB1: 0x1F399,  # studio microphone
        0xB2: 0x1F3A7,  # headphone
        0xB3: 0x1F4BF,  # optical disc
        0xB4: 0x1F39E,  # film frames
        0xB5: 0x1F4F7,  # camera
        0xB6: 0x1F39F,  # admission tickets
        0xB7: 0x1F3AC,  # clapper board
        0xB8: 0x1F4FD,  # film projector
        0xB9: 0x1F4F9,  # video camera
        0xBA: 0x1F4FE,  # portable stereo
        0xBB: 0x1F4FB,  # radio
        0xBC: 0x1F39A,  # level slider
        0xBD: 0x1F39B,  # control knobs
        0xC0: 0x1F5A5,  # desktop computer
        0xC1: 0x1F5A6,  # keyboard and mouse
        0xC2: 0x1F5A7,  # three networked computers
        0xC3: 0x1F579,  # joystick
        0xC5: 0x1F57B,  # left hand telephone receiver
        0xC6: 0x1F57C,  # telephone receiver with page
        0xC8: 0x1F581,  # clamshell mobile phone
        0xC9: 0x1F580,  # telephone on top of modem
        0xCA: 0x1F5A8,  # printer
        0xCB: 0x1F5A9,  # pocket calculator
        0xCC: 0x1F5BF,  # black folder
        0xCD: 0x1F5AA,  # black hard shell floppy disk
        0xCE: 0x1F5DC,  # compression
        0xCF: 0x1F512,  # lock
        0xD0: 0x1F513,  # open lock
        0xD1: 0x1F511,  # key
        0xD2: 0x1F4E5,  # inbox tray
        0xD3: 0x1F4E4,  # outbox tray
        0xD5: 0x1F323,  # white sun
        0xDE: 0x1F32C,  # wind blowing face
        0xDF: 0x1F32B,  # fog
        0xE0: 0x1F31C,  # last quarter moon with face
        0xE1: 0x1F321,  # thermometer
        0xE2: 0x1F6CB,  # couch and lamp
        0xE5: 0x1F378,  # cocktail glass
        0xE6: 0x1F6CE,  # bellhop bell
        0xE9: 0x267F,  # wheelchair symbol
        0xEA: 0x1F6C6,  # triangle with rounded corners
        0xEB: 0x1F588,  # black pushpin
        0xEC: 0x1F393,  # graduation cap
        0xED: 0x1F5E4,  # three rays above
        0xEE: 0x1F5E5,  # three rays below
        0xEF: 0x1F5E6,  # three rays left
        0xF0: 0x1F5E7,  # three rays right
        0xF2: 0x1F43F,  # chipmunk
        0xF3: 0x1F426,  # bird
        0xF4: 0x1F41F,  # fish
        0xF5: 0x1F415,  # dog
        0xF6: 0x1F408,  # cat
        0xF7: 0x1F66C,  # leftwards rocket
        0xF8: 0x1F66E,  # rightwards rocket
        0xF9: 0x1F66D,  # upwards rocket
        0xFA: 0x1F66F,  # downwards rocket
        0xFB: 0x1F5FA,  # world map
        0xFC: 0x1F30D,  # earth globe europe-africa
        0xFD: 0x1F30F,  # earth globe asia-australia
        0xFE: 0x1F30E,  # earth globe americas
        0xFF: 0x1F54A,  # dove of peace
    },
}
