"""Text in a Microsoft symbol face, drawn without the face.

Symbol, Wingdings, Wingdings 2, Wingdings 3 and Webdings encode pictures where other faces
have letters.  A bullet ``<a:buFont typeface="Wingdings"/><a:buChar char="q"/>`` is a
shadowed box, a Wingdings run ``ü`` a check mark -- and a renderer whose host lacks the
face draws "q" and "ü".  Office writes the characters either as the code itself
(0x20..0xFF, PowerPoint's ``buChar`` and runs) or as its private-use alias U+F020..U+F0FF
(Word's ``w:sym`` and bullets); both mean the same glyph.

:func:`to_unicode` turns such text into the Unicode characters it stands for: Unicode's own
identification of every glyph (:mod:`.symbol_maps`, generated by
``tools/derive_symbol_maps.py`` from the Unicode Consortium's published tables), under a
handful of drawing preferences (:data:`PREFERRED`).  :data:`FALLBACK_FAMILIES` is the stack
that draws the result.  A renderer maps only a face it cannot draw itself -- where the
face is installed, embedded or supplied, its own glyphs are the faithful answer -- and says
so.  :func:`recorded_font_metrics` lays Symbol and Wingdings out at their own advances
meanwhile (:mod:`.recorded_symbol_faces`), so the text around a symbol stays where the
application put it.
"""

from __future__ import annotations

from .metrics import FontMetrics
from .symbol_maps import MAPS

#: The symbol faces, keyed without spaces or case (``"wingdings2"``), to the key of their
#: table in :data:`~.symbol_maps.MAPS`.
SYMBOL_FACES = {
    "symbol": "symbol",
    "wingdings": "wingdings",
    "wingdings2": "wingdings 2",
    "wingdings3": "wingdings 3",
    "webdings": "webdings",
}

#: Drawing preferences over Unicode's identification: the bullets and marks of the Office
#: bullet libraries, as the long-standing characters the faces on any host carry, where
#: the identification names a newer one few faces have (Wingdings' ``l``, U+26AB MEDIUM
#: BLACK CIRCLE, is drawn as U+25CF BLACK CIRCLE, the size PowerPoint draws it) -- each
#: compared with PowerPoint 16's export of pptx2svg's ``tools/make_symbol_probe.py``, and
#: named as in the Unicode character database.  ``ü`` stays U+2713 CHECK MARK: the glyph
#: PowerPoint draws is the light check, not U+2714 HEAVY CHECK MARK.
PREFERRED: dict[str, dict[int, str]] = {
    "wingdings": {
        0x6C: "\u25cf",  # BLACK CIRCLE
        0x6E: "\u25a0",  # BLACK SQUARE
        0x6F: "\u25a1",  # WHITE SQUARE
        0x71: "\u2751",  # LOWER RIGHT SHADOWED WHITE SQUARE
        0x75: "\u25c6",  # BLACK DIAMOND
        0x76: "\u2756",  # BLACK DIAMOND MINUS WHITE X
        0xA7: "\u25aa",  # BLACK SMALL SQUARE
        0xD8: "\u27a2",  # THREE-D TOP-LIGHTED RIGHTWARDS ARROWHEAD
        0xE8: "\u2794",  # HEAVY WIDE-HEADED RIGHTWARDS ARROW
        0xFC: "\u2713",  # CHECK MARK
        0xFE: "\u2611",  # BALLOT BOX WITH CHECK
    },
}

#: Faces that draw what :func:`to_unicode` returns, best first: Windows', macOS' (Apple
#: Symbols, and Zapf Dingbats for the Dingbats block), then the open families a server is
#: likely to have.  Unicode 7.0's additions for these sets are in Segoe UI Symbol and
#: Noto Sans Symbols 2.
FALLBACK_FAMILIES = (
    "Segoe UI Symbol",
    "Apple Symbols",
    "Zapf Dingbats",
    "Noto Sans Symbols 2",
    "Noto Sans Symbols",
    "DejaVu Sans",
    "Symbola",
)


def symbol_face(family: str | None) -> str | None:
    """The :data:`~.symbol_maps.MAPS` key of ``family`` when it names a symbol face
    (``"Wingdings 2"`` -> ``"wingdings 2"``), else ``None``."""
    if not family:
        return None
    return SYMBOL_FACES.get("".join(family.split()).lower())


def code_of(char: str) -> int | None:
    """The face's code (0x20..0xFF) a character stands for: itself, or its private-use
    alias U+F020..U+F0FF.  ``None`` for anything else."""
    point = ord(char)
    if 0xF020 <= point <= 0xF0FF:
        point -= 0xF000
    return point if 0x20 <= point <= 0xFF else None


def to_unicode(face: str, char: str) -> str | None:
    """What ``char`` in symbol face ``face`` (a :func:`symbol_face` key) is, as Unicode
    text, or ``None`` when the glyph has no equivalent."""
    code = code_of(char)
    if code is None:
        return None
    preferred = PREFERRED.get(face, {}).get(code)
    if preferred is not None:
        return preferred
    point = MAPS.get(face, {}).get(code)
    return chr(point) if point is not None else None


def translate(face: str, text: str) -> tuple[str, str]:
    """``text`` in ``face`` as the Unicode it stands for, and the characters that have no
    equivalent (left as they are).  Characters outside the face's codes -- a space typed
    as U+00A0 aside, which is 0xA0 -- pass through."""
    out: list[str] = []
    unmapped: list[str] = []
    for char in text:
        if char in "\n\t":
            out.append(char)
            continue
        mapped = to_unicode(face, char)
        if mapped is None:
            if code_of(char) is not None and char != " ":
                unmapped.append(char)
            out.append(char)
        else:
            out.append(mapped)
    return "".join(out), "".join(unmapped)


def recorded_font_metrics(face: str) -> FontMetrics | None:
    """A measurer's table for an absent Symbol or Wingdings, from the advances recorded
    from Word's copy (:mod:`.recorded_symbol_faces`): every code at its glyph's advance,
    under both of its spellings.  ``None`` for a face nothing was recorded for."""
    from . import recorded_symbol_faces as recorded

    metrics = recorded.METRICS.get(face)
    advances = recorded.ADVANCES.get(face)
    if metrics is None or advances is None:
        return None
    units_per_em, ascent, descent = metrics[0], metrics[1], metrics[2]
    widths: dict[str, int] = {}
    for point, advance in advances.items():
        code = code_of(chr(point))
        if code is None:
            continue
        widths.setdefault(chr(code), advance)
        widths.setdefault(chr(0xF000 + code), advance)
    mean = round(sum(advances.values()) / len(advances)) if advances else units_per_em // 2
    return FontMetrics(
        units_per_em=units_per_em,
        ascender=ascent,
        descender=-descent,
        default_width=mean,
        cjk_width=units_per_em,
        widths=widths,
        line_gap=metrics[3],
    )
